/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package plg.proto;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 2;
  /** RegularExpression Id. */
  int AND = 3;
  /** RegularExpression Id. */
  int IF = 4;
  /** RegularExpression Id. */
  int FI = 5;
  /** RegularExpression Id. */
  int THEN = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int TRUE = 8;
  /** RegularExpression Id. */
  int FALSE = 9;
  /** RegularExpression Id. */
  int WRITE = 10;
  /** RegularExpression Id. */
  int PAP = 11;
  /** RegularExpression Id. */
  int PCIERRE = 12;
  /** RegularExpression Id. */
  int STRING = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"or\"",
    "\"and\"",
    "\"if\"",
    "\"fi\"",
    "\"then\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"write\"",
    "\"(\"",
    "\")\"",
    "<STRING>",
  };

}
